# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3cff5234ea8070d403a7ba4329b647c219dd9a1a1ddaaba97a092ba43984896d93e7f9383c121eca1e698694e5f71454dab2a17707b6047bb9e479dc82ea11f1

test:
  secret_key_base: 4fd3d00536abebacf10f0d0d64f7a288bd0908ed62c39a04d2b9dbd9af0706334a8fd33aa8d79ab2569e199165015c4bc0618fa839104fe5b880973146e8da9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
